FROM node:alpine3.11 as builder
ARG EXPRESS_HOST
ARG NODE_ENV
WORKDIR /usr/src/frontend
COPY package*.json ./
RUN yarn install
COPY . .
RUN echo "HOST: $EXPRESS_HOST and ENV: ${NODE_ENV}"
RUN EXPRESS_HOST=${EXPRESS_HOST} \
    NODE_ENV=${NODE_ENV} \
    yarn build

FROM nginx:1.21-alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]